### ISSUE TITLE
Unable to open file

### ISSUE THREAD

**Issue by lovasoa** [pgroubioinfo/pgrou#53]
When compiling these sources and opening any file in the "sample" folder, we get an error.

Are these sources up-to-date ? What works and what doesn't?

Ophir

**Comment by AurelienHP** [comment]
Bonne question...

**Comment by lovasoa** [comment]
Wow! Réponse rapide, au moins :)

**Comment by lovasoa** [comment]
Vous vous en étiez arrêté où? Vous aviez un truc qui marchait?

**Comment by MFolschette** [comment]
Hello,

Actuellement, gPH a (au moins) un problème de compatibilité avec la dernière version de GraphViz, et cela n'a pas encore été corrigé. Êtes-vous sûr que la compilation s'est bien déroulée ?

Le versionnage de ce logiciel n'est pas encore vraiment au point et la dernière version est sur ce dépôt : https://github.com/PAPPLBioInformatique/PAPPL
Cependant, elle a le même problème.

**Comment by lovasoa** [comment]
Oui, j'ai fixé le problème de compilation avec graphviz

**Comment by lovasoa** [comment]
Et j'ai fait le port vers Qt5

**Comment by MFolschette** [comment]
En dehors de ce problème, cette version était fonctionnelle à ma connaissance. Peut-être est-ce lié à Qt ou à Boost.

Serait-il possible d'avoir davantage de précisions ? Quel est l'intitulé exact de l'erreur ?

**Comment by lovasoa** [comment]
Voilà où j'en suis: https://github.com/lovasoa/pgrou/tree/qt5

**Comment by lovasoa** [comment]
L'erreur que l'on obtient à l'ouverture d'un fichier est celle-ci: https://github.com/pgroubioinfo/pgrou/blob/master/src/ph/PH.cpp#L57

**Comment by MFolschette** [comment]
Avez-vous bien installé Pint ? Et ses exécutables sont-ils dans le $PATH ? J'ai l'impression que le problème bien du parsing.

**Comment by lovasoa** [comment]
> Avez-vous bien installé Pint ? Et ses exécutables sont-ils dans le $PATH ?

Oui

**Comment by lovasoa** [comment]
C'est en fait cette erreur qui est levée: https://github.com/pgroubioinfo/pgrou/blob/master/src/gfx/PHScene.cpp#L51

Voilà une stack-trace:

```
#0  0x00007ffff5ba70dd in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x0000000000420310 in PHScene::getGSort (this=0xad6910, s="eps8rpip3pi3krsos1r") at src/gfx/PHScene.cpp:51
#2  0x0000000000418d47 in GAction::initContactPoints (this=this@entry=0x10949f0) at src/gfx/GAction.cpp:64
#3  0x000000000041c016 in GAction::GAction (this=0x10949f0, a=..., sc=<optimized out>) at src/gfx/GAction.cpp:15
#4  0x0000000000421a68 in boost::make_shared<GAction, boost::shared_ptr<Action>&, PHScene*>(boost::shared_ptr<Action>&, PHScene*&&) (arg1=...)
    at /usr/include/boost/smart_ptr/make_shared_object.hpp:218
#5  0x000000000041fee0 in PHScene::createActions (this=this@entry=0xad6910) at src/gfx/PHScene.cpp:77
#6  0x00000000004208af in PHScene::drawFromSkeleton (this=0xad6910) at src/gfx/PHScene.cpp:39
#7  0x0000000000438c1d in PH::render (this=0x998c20) at src/ph/PH.cpp:29
#8  0x0000000000445150 in MainWindow::openTab (this=0x7fffffffdc20) at src/ui/MainWindow.cpp:303
#9  0x0000000000476c79 in MainWindow::qt_static_metacall (_o=0x7fffffffdc20, _c=<optimized out>, _id=<optimized out>, _a=0x7fffffffd5d0) at moc_MainWindow.cpp:170
#10 0x00007ffff615c27d in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#11 0x00007ffff6df7902 in QAction::triggered(bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x00007ffff6df9f88 in QAction::activate(QAction::ActionEvent) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x00007ffff615d12a in QObject::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x00007ffff6dfa4f1 in QAction::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007ffff6dff16c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007ffff6e0441e in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00007ffff612d81b in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#18 0x00007ffff612f7e3 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#19 0x00007ffff6184a63 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#20 0x00007ffff40d5c5d in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#21 0x00007ffff40d5f48 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#22 0x00007ffff40d5ffc in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#23 0x00007ffff6184e57 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#24 0x00007ffff612b042 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#25 0x00007ffff6132acc in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#26 0x0000000000415906 in main (argc=1, argv=<optimized out>) at src/Main.cpp:22
```

**Comment by lovasoa** [comment]
Ok, I fixed the problem. I had introduced it while porting to the latest graphviz.
Here is the fix : https://github.com/lovasoa/pgrou/commit/3659c05bbe8a0844b4e5a00c9b8f667082eb54fd

Now it compiles with a recent graphviz and a recent version of Qt.

Sorry for the inconvenience.

**Comment by MFolschette** [comment]
Solving bugs never is an inconveninence!

Thanks for the update!
